### PR TITLE
Replace POST by PUT

### PR DESCRIPTION
**Pull request by roelandkulk**

### CODE REVIEW

**Comment by roelandkulk** [comment]
@pschildkamp I'm again a bit stuck with the unit tests so when you have some time I would like to discuss those.

**Comment by roelandkulk** [comment]
I'm aware that the AbstractSecurityInterceptor still needs some work.

**Comment by roelandkulk** [comment]
I have moved logic from SchoolResource to the service. The tradeoff is now that there is no different status code now for create vs update. 
This still has to be applied to GuestTeacher

**Review by pschildkamp — APPROVED** [review]
:)

**Pull request merged**
